### ISSUE TITLE
[Edit Suggestion] Moving Your Site to a New Server, or to Root from Subfolder

### ISSUE THREAD

**Issue by eiger3970** [modxcms/docs#104]
## Page Title

Moving Your Site to a New Server, or to Root from Subfolder
## URL

https://rtfm.modx.com/revolution/2.x/administering-your-site/moving-your-site-to-a-new-server
## Issue or Suggestion

Writable: 777 or 755?
Some of the folders need to be may writable.

should read

Writable: 777 or 755?
Some of the folders may need to be writable.

**Comment by Mark-H** [comment]
Fixed
