### ISSUE TITLE
Filename Typo

### ISSUE THREAD

**Issue by r-leclair** [modxcms/docs#105]
## Page Title

Git Installation
## URL

https://rtfm.modx.com/revolution/2.x/getting-started/installation/git-installation
## Issue or Suggestion

Section entitled "Run the Build" there is a direction to copy/rename the file '_build/build.sample.properties.php' to '_build/build.properties.php' when in fact this should read '_build/build.properties.sample.php' to '_build/build.properties.php' this may be trivial (?) but confusion is added as within the same directory there exists also a file named 'build.sample.properties'. just fyi -rich

**Comment by pixelchutes** [comment]
Thanks for filing this, has always confused me as well.

This has been [fixed](https://rtfm.modx.com/revolution/2.x/getting-started/installation/git-installation). Per your suggestion, I changed the reference of `build.sample.properties.php` to `build.properties.sample.php`, as `build.sample.properties.php` file does not exist.
