### ISSUE TITLE
[Edit Suggestion] The Manager

### ISSUE THREAD

**Issue by Sergey1050** [modxcms/docs#114]
[!menu?type=`american`!]
Итальянская кухня

[!menu?type=`italian`!]
Бизнес-ланч

[!menu?type=`lunch`!]
Премиум Бизнес-ланч

[!menu?type=`premium`!]

http:/http://beefhouse.ru//

Как редактироватьтакую конструкцию на ресурсе меню ресторана надо поменять названия блюд и их цены уже 3 дня мучаюсь ничего не помогает этот сайт мне передали в управление но я не знаком с данной СМС а в документации я ничего похожего не нашел. Помогите пожалуйста.

**Comment by Mark-H** [comment]
This repository is for reporting specific issues with the documentation. Please consult your developer, the MODX forums at forums.modx.com or the community on Slack via modx.org if you need help.
