### ISSUE TITLE
[Edit Suggestion] OnBeforeDocFormSave

### ISSUE THREAD

**Issue by intersel** [modxcms/docs#120]
## Page Title

OnBeforeDocFormSave
## URL

https://rtfm.modx.com/revolution/2.x/developing-in-modx/basic-development/plugins/system-events/onbeforedocformsave
## Issue or Suggestion

remove bad ')' in 
Examples
Require a Field

```
?
if (empty($resource->longtitle)) {
        $modx->event->output('Long title is required!'); // to modal window
        return '[MyPlugin] Failed to save page id '.$id.' due to missing longtitle'--->>>)<<<---; // to the error log
}
```

**Comment by intersel** [comment]
Well, when I tried this example, and after the above fix, I stumbled to another problem...

The manager hanged with this error: `"Uncaught SyntaxError: Unexpected token <"`
giving me this return on the 'return/update' processor:

```
(<h5>[2015-11-11 00:57:01] (ERROR @ /connectors/index.php)</h5><pre>[OnBeforeDocFormSave][MyPlugin] Failed to save page id 956 due to missing longtitle</pre>
{"success":false,"message":"Long title is required!\n","total":0,"data":[],"object":[]})
```

I thought this string would have been saved in the log but... sounds to go to the output of the processor...?

So I don't know what to say... perhaps remove the string in the return part of the example...? perhaps it is a problem in my config?

**Comment by Mark-H** [comment]
The $modx->event->output() line would go to the message, but the return should definitely go to the log. If not that might warrant further investigation.

**Comment by Mark-H** [comment]
Fixed the wrongfully placed ) in the doc.
