### ISSUE TITLE
Properties link_tag_scheme on GoogleSiteMap for HTTPS scheme

### ISSUE THREAD

**Issue by gitrequests** [modxcms/docs#123]
## Add properties &scheme

Add properties &scheme or &linkScheme to snippet. I use sitemap on HTTPS protocol and i edit this line of code (file - googlesitemap.class.php, line - 103, 4 parameter of makeUrl function):

``` PHP
$url = $this->modx->makeUrl($id,'','','https');
```

Available link_tag_schemes in MODX:
https://rtfm.modx.com/revolution/2.x/administering-your-site/settings/system-settings/link_tag_scheme

**Comment by Mark-H** [comment]
Please report this to the author of the GoogleSiteMap plugin. This repository is only for documentation issues. Thanks!
