### ISSUE TITLE
[Edit Suggestion] Successful Installation, Now What Do I Do?

### ISSUE THREAD

**Issue by kaushickacademy** [modxcms/docs#127]
## Page Title

Successful Installation, Now What Do I Do?
## URL

https://rtfm.modx.com/revolution/2.x/getting-started/installation/successful-installation,-now-what-do-i-do

**Comment by Mark-H** [comment]
Appears to be waaaaaaay old and lacking images.

**Comment by Mark-H** [comment]
Dupe of #35
