### ISSUE TITLE
Action List

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#13]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [10697](https://modx.zendesk.com/agent/#/tickets/10697)
**Priority:** 
**Zendesk assignee:** MODX Support/A

**Original ticket content:**

-- ISSUE DETAILS --
Action List (342)
http://rtfm.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-manager-pages/actions-and-menus/action-list.

Verstuurd vanaf mijn iPhone

**Comment by jaygilmore** [comment]
*Comment from Zendesk by v.zondag@icloud.com at 2014-12-07 05:29:59 UTC:*

<p>-- ISSUE DETAILS --
<br />Action List (342)
<br /><a href="http://rtfm.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-manager-pages/actions-and-menus/action-list" rel="nofollow" target="_blank">http://rtfm.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-manager-pages/actions-and-menus/action-list</a>.</p>

<p>Verstuurd vanaf mijn iPhone</p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2014-12-08 17:44:55 UTC:*

<p>Thanks for the report. We will review and fix as soon as time permits.</p>
<p>All the best,</p>
<p>Jay</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by Mark-H** [comment]
That particular page seems up-to-date and accurate to me.. any more details from the ticket about what's up with it?

**Comment by jaygilmore** [comment]
Sorry. This is not a valid issue and was likely spam test.
