### ISSUE TITLE
Redirector

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#14]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [10685](https://modx.zendesk.com/agent/#/tickets/10685)
**Priority:** 
**Zendesk assignee:** MODX Support/A

**Original ticket content:**

Needs to point to…

https://github.com/modxcms/Redirector

-- ISSUE DETAILS --

Redirector (698)

http://rtfm.modx.com/extras/revo/redirector.

**Comment by jaygilmore** [comment]
*Comment from Zendesk by bwente@fairwinds.org at 2014-12-05 21:07:25 UTC:*

<p>Needs to point to…</p>

<p><a href="https://github.com/modxcms/Redirector" rel="nofollow" target="_blank">https://github.com/modxcms/Redirector</a></p>

<p>-- ISSUE DETAILS --</p>

<p>Redirector (698)</p>

<p><a href="http://rtfm.modx.com/extras/revo/redirector" rel="nofollow" target="_blank">http://rtfm.modx.com/extras/revo/redirector</a>.</p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2014-12-08 17:44:55 UTC:*

<p>Thanks for the report. We will review and fix as soon as time permits.</p>
<p>All the best,</p>
<p>Jay</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by Mark-H** [comment]
Links have been updated

**Comment by jaygilmore** [comment]
Thanks Mark. Closed.
