### ISSUE TITLE
[Edit Suggestion] Plugins

### ISSUE THREAD

**Issue by carnevlu** [modxcms/docs#149]
## Page Title

Plugins
## URL

https://rtfm.modx.com/revolution/2.x/developing-in-modx/basic-development/plugins
## Issue with the example `->_output` alteration

This example is currently not working.

``` php
$words = array("snippet", "template"); // words to filter
$output = &$modx->resource->_output; // get a reference to the output
$output = str_replace($words,"<b>[filtered]</b>",$output);
```

The probable reason is that `$_output` variable is _private_.
<img width="890" alt="screen shot 2016-02-09 at 11 37 51" src="https://cloud.githubusercontent.com/assets/3392707/12913905/a7d5cb8e-cf21-11e5-8a1d-e632526515f7.png">

**Comment by Mark-H** [comment]
`modResource->_output` is public
