### ISSUE TITLE
[Edit Suggestion] EvoGallery

### ISSUE THREAD

**Issue by jorjik** [modxcms/docs#151]
## Page Title

EvoGallery
## URL

https://rtfm.modx.com/extras/evo/evogallery
## Issue or Suggestion

BUG: Failed to load resource: the server responded with a status of 404 (Not Found) /assets/js/jquery-1.3.2.min.js

Call: [[EvoGallery? &display=`images` &type=`jquery-cycle`]]

**Comment by Mark-H** [comment]
This repository is only for bugs with the documentation. Issues with extras should be reported to their maintainers. For EvoGallery there's this repo you can report issues at https://github.com/Mark-H/EvoGallery/issues however I don't personally maintain it anymore.
