### ISSUE TITLE
[Edit Suggestion] Filing Bug Reports

### ISSUE THREAD

**Issue by ravindra008** [modxcms/docs#152]
## Page Title

Filing Bug Reports

Hello there,

I am Ravindra Singh Rathore. I have found a security vulnerability in MODX 2.4.3 and I think it is not the right place to disclose it. Please contact me as rsrathoreravi@gmail.com for more details.

Thanks
Ravindra

**Comment by Jako** [comment]
Mail it to security@modx.com
