### ISSUE TITLE
[Edit Suggestion] Database Connections and xPDO

### ISSUE THREAD

**Issue by sergant210** [modxcms/docs#162]
## Page Title

Database Connections and xPDO
## URL

https://rtfm.modx.com/xpdo/2.x/getting-started/using-your-xpdo-model/database-connections-and-xpdo
## Issue or Suggestion

Error in line
`$dsn = 'mysql:host=localhost;dbname=test;port=3306;charset=utf-8';`
Must be '...charset=utf8'

**Comment by Mark-H** [comment]
Corrected, thanks.
