### ISSUE TITLE
[Edit Suggestion] Custom Manager Pages Tutorial

### ISSUE THREAD

**Issue by janwidmer** [modxcms/docs#163]
## Page Title

Custom Manager Pages Tutorial
## URL

https://rtfm.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-manager-pages/custom-manager-pages-tutorial
## Issue or Suggestion

The concept of the actions is deprecated since modx 2.3+. It would be nice, if the Section "Create the Action" could be removed and the section "Create the Menu Object" adjusted accordingly. People who do not now about actions being deprecated are searching for the actions and cannot find them.

**Comment by sebastian-marinescu** [comment]
Hi @janwidmer 

I've edited the beginning of that RTFM-tutorial to point to the CMP-Tutorial for newer MODX-Versions. I think this is sufficient and the _deprecated_ sections should stay as is, because of backwards-compatibility. 

So the issue can be closed again, if you're okay with that.
