### ISSUE TITLE
[Edit Suggestion] allow_duplicate_alias

### ISSUE THREAD

**Issue by nicar** [modxcms/docs#164]
## Page Title

allow_duplicate_alias
## URL

https://rtfm.modx.com/revolution/2.x/administering-your-site/settings/system-settings/allow_duplicate_alias
## Issue or Suggestion

Add note: Deprecated since version 2.1
See https://github.com/modxcms/revolution/issues/11143
Maybe add annotation _allow_duplicate_alias **(deprecated v.2.1)**_ to system setting list as well

**Comment by Mark-H** [comment]
Added a quick note to say it was removed, thanks!
