### ISSUE TITLE
[Edit Suggestion] Quip.Quip.tplComment

### ISSUE THREAD

**Issue by lukemcd** [modxcms/docs#165]
## Page Title

Quip.Quip.tplComment
## URL

https://rtfm.modx.com/extras/revo/quip/quip.quip/quip.quip.tplcomment
## Issue or Suggestion

Under Available Placeholders add:

```
Name: resource
Description: The ID of the resource associated with the thread of this comment.
```

This is particularly helpful when displaying comments on other pages so the template can contain [[~[[+resource]]]] to link back to the original article where the comment came from.

**Comment by Mark-H** [comment]
Added, thanks.
