### ISSUE TITLE
FormIt Submit Var Issue

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#17]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [10707](https://modx.zendesk.com/agent/#/tickets/10707)
**Priority:** 
**Zendesk assignee:** MODX Support/A

**Original ticket content:**

-- ISSUE DETAILS -- FormIt (644) http://rtfm.modx.com/extras/revo/formit.

Hello!

When working with multiple forms on page and using &submitVar=`to_me` parameter, tag <input type="submit" name="to_me" value="Send to me" /> works correctly, but the <button type="submit" name="to_me">Send to me</button> does not work. It unexpectedly.

Sincerely, Evgeniy.

**Comment by jaygilmore** [comment]
*Comment from Zendesk by iscx@yandex.ru at 2014-12-08 08:51:56 UTC:*

<p>-- ISSUE DETAILS -- FormIt (644) <a href="http://rtfm.modx.com/extras/revo/formit" rel="nofollow" target="_blank">http://rtfm.modx.com/extras/revo/formit</a>.</p>

<p>Hello!</p>

<p>When working with multiple forms on page and using &amp;submitVar=`to_me` parameter, tag &lt;input type=&quot;submit&quot; name=&quot;to_me&quot; value=&quot;Send to me&quot; /&gt; works correctly, but the &lt;button type=&quot;submit&quot; name=&quot;to_me&quot;&gt;Send to me&lt;/button&gt; does not work. It unexpectedly.</p>

<p>Sincerely, Evgeniy.</p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2014-12-08 17:44:54 UTC:*

<p>Thanks for the report. We will review and fix as soon as time permits.</p>
<p>All the best,</p>
<p>Jay</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by dubrod** [comment]
noted
