### ISSUE TITLE
[Edit Suggestion] Resetting a User Password Manually

### ISSUE THREAD

**Issue by alexseif** [modxcms/docs#170]
## Page Title

Resetting a User Password Manually
## URL

https://rtfm.modx.com/revolution/2.x/administering-your-site/security/troubleshooting-security/resetting-a-user-password-manually
## Issue or Suggestion

The API is not working, I keep getting "ERROR: No user with username admin"

**Comment by Mark-H** [comment]
That error seems pretty self descriptive... if you do think there should be an account with that username, then there might be an issue (connecting with) your database. Check the MODX error log for more info, and get help via the MODX forums.

**Comment by Mark-H** [comment]
(Also to clarify, I'm closing this here because it's for issues related to the _documentation_. This issue does not mention any documentation issues)

**Comment by alexseif** [comment]
Sorry, if I'm commenting in the wrong section, however this is in the documentation.
1) there are no issues with connectivity.
2) there are no errors in the log.
3) the user exists and is active. 
This is the first time for me to user MODx, and I downloaded a running version from a client, and I simply want to generate a new password for the admin panel, to run locally.
