### ISSUE TITLE
Moving Your Site to a New Server, or to Root from Subfolder

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#18]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [10702](https://modx.zendesk.com/agent/#/tickets/10702)
**Priority:** 
**Zendesk assignee:** MODX Support/A

**Original ticket content:**

Hi,

There is NO "Site" and "Security" and "Flush All Sessions" in the manager. They have different names... In RTFM there are these lines:
Log into the manager, then: Site --> Clear Cache
Clear your sessions: Security --> Flush All Sessions

I can see "Flush Your Permissions - Reload this session’s Permissions" and "Logout All Users - Immediately destroy all sessions",

so, do I Flush what, sessions or destory permissions?

thank you.

-- ISSUE DETAILS --
Moving Your Site to a New Server, or to Root from Subfolder (206)
http://rtfm.modx.com/revolution/2.x/administering-your-site/moving-your-site-to-a-new-server.

Best regards,
Alex.

**Comment by jaygilmore** [comment]
*Comment from Zendesk by nervenom@gmail.com at 2014-12-07 16:21:16 UTC:*

<p>Hi,</p>

<p>There is NO &quot;Site&quot; and &quot;Security&quot; and &quot;Flush All Sessions&quot; in the manager. They have different names... In RTFM there are these lines:
<br />Log into the manager, then: Site --&gt; Clear Cache
<br />Clear your sessions: Security --&gt; Flush All Sessions</p>

<p>I can see &quot;Flush Your Permissions - Reload this session’s Permissions&quot; and &quot;Logout All Users - Immediately destroy all sessions&quot;,</p>

<p>so, do I Flush what, sessions or destory permissions?</p>

<p>thank you.</p>

<p>-- ISSUE DETAILS --
<br />Moving Your Site to a New Server, or to Root from Subfolder (206)
<br /><a href="http://rtfm.modx.com/revolution/2.x/administering-your-site/moving-your-site-to-a-new-server" rel="nofollow" target="_blank">http://rtfm.modx.com/revolution/2.x/administering-your-site/moving-your-site-to-a-new-server</a>.</p>

<p>Best regards,
<br />Alex.</p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2014-12-08 17:44:54 UTC:*

<p>Thanks for the report. We will review and fix as soon as time permits.</p>
<p>All the best,</p>
<p>Jay</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by dubrod** [comment]
updated
