### ISSUE TITLE
[Edit Suggestion] modX.toPlaceholders

### ISSUE THREAD

**Issue by mintnl** [modxcms/docs#183]
## Page Title
modX.toPlaceholders

## URL
https://docs.modx.com/revolution/2.x/developing-in-modx/other-development-resources/class-reference/modx/modx.toplaceholders

## Issue or Suggestion

in the part about nested placeholders:

`$modx->toPlaceholders(array(
  'document' => , array('pagetitle' => 'My Page')
));`

the extra comma before "array(...." needs to be removed: 
`$modx->toPlaceholders(array(
  'document' => array('pagetitle' => 'My Page')
));`

Same for example below:

`$modx->toPlaceholders(
  array(
    'test' => 'this',
    'document' => array('pagetitle' => 'My Page')
  ), 'tmp'
);`

**Comment by Jako** [comment]
Done. Thanks for your correction.
