### ISSUE TITLE
Server Requirements for Extras

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#20]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [9974](https://modx.zendesk.com/agent/#/tickets/9974)
**Priority:** low
**Zendesk assignee:** MODX Support/Jay Gilmore

**Original ticket content:**

RTFM Document Issue Report

Reporter: Gordon
Email: g.pretorius@cergis.com
Pagetitle: Server Requirements
URL: http://rtfm.modx.com/revolution/2.x/getting-started/server-requirements
ID: 273

Comments:
You need to enable "php-mbstring" on the server for the gallery to work. This should be added as a requirement to the requirements page as we just spent quite a bit of time figuring this out :)

**Comment by jaygilmore** [comment]
*Comment from Zendesk by g.pretorius@cergis.com at 2014-10-16 10:39:02 UTC:*

<p>RTFM Document Issue Report</p>

<p>Reporter: Gordon
<br />Email: <a href="mailto:g.pretorius@cergis.com">g.pretorius@cergis.com</a>
<br />Pagetitle: Server Requirements
<br />URL: <a href="http://rtfm.modx.com/revolution/2.x/getting-started/server-requirements" rel="nofollow" target="_blank">http://rtfm.modx.com/revolution/2.x/getting-started/server-requirements</a>
<br />ID: 273</p>

<p>Comments:
<br />You need to enable &quot;php-mbstring&quot; on the server for the gallery to work. This should be added as a requirement to the requirements page as we just spent quite a bit of time figuring this out :)</p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2014-10-16 15:18:53 UTC:*

<p>Hi Gordon,</p>
<p>Thanks for this report. What would you think about adding the requirement to documentation for Gallery?</p>
<p>It is not required to run MODX at all, however a few 3rd party Extras do require it and they should state that requirement or as is the case of AjaxSearch, provide fallback functionality when it&#39;s not available.</p>
<p>I&#39;d love to hear your thoughts.</p>
<p>All the best,</p>
<p>Jay</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by g.pretorius@cergis.com at 2014-10-16 15:40:09 UTC:*

<p>Hi Jay,</p>

<p>I agree it should be added to the Gallery section as well, but it would be really helpful if all requirements are listed on a single page. e.g.</p>

<p>Requirements
<br />1. xxx
<br />2. xxx
<br />3. Enable &quot;php-mbstring&quot; (required for Gallery, AjaxSearch...)</p>

<p>This should only be done for major third party plugins. Point being, we had a separate agency setting up the hosting environment as it was a very secure environment and they simply reference the core requirements page to see what features are needed for a production environment.</p>

<p>I cannot imagine anyone using a CMS without using the gallery? It&#39;s more of a core function.</p>

<p>Let me know your thoughts</p>

<p>Regards</p>

<p>Gordon</p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2014-11-18 22:00:54 UTC:*

<p>Gordon,</p>
<p>We&#39;ve still not implemented this but haven&#39;t forgotten about it. I am going to put it on hold but keep it open until we can rectify it.</p>
<p>All the best,</p>
<p>Jay</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by dubrod** [comment]
added
