### ISSUE TITLE
[Edit Suggestion] compress_css

### ISSUE THREAD

**Issue by jpdevries** [modxcms/docs#201]
## Page Title
compress_css

## URL
https://docs.modx.com/revolution/2.x/administering-your-site/settings/system-settings/compress_css

## Issue or Suggestion
compress_css fundamentally changed in 2.5. Now it just ships a pre-built single file and does not use server side concat and minify.

**Comment by Mark-H** [comment]
The linked page doesn't mention it being dynamically compressed, so someone must've fixed this already.
