### ISSUE TITLE
[Edit Suggestion] Mailgun integration

### ISSUE THREAD

**Issue by stefany-newman** [modxcms/docs#202]
## Page Title
Mailgun integration

## URL
https://docs.modx.com/extras/revo/virtunewsletter/mailgun-integration

## Issue or Suggestion
Invalid URL of the mailgun Github. Should be https://github.com/mailgun/mailgun-php 
Somehow the parsing engine adds the coma to the end of the URL.

**Comment by Mark-H** [comment]
Fixed. Thanks for logging the issue.
