### ISSUE TITLE
[Edit Suggestion] Caching

### ISSUE THREAD

**Issue by ostryanyn** [modxcms/docs#206]
## Page Title
Caching

## URL
https://docs.modx.com/revolution/2.x/developing-in-modx/advanced-development/caching#highlighter_451227

## Issue or Suggestion
Code in the example is missing a `)` bracket:

`// refresh the web and web2 context_settings only`
`$modx->cacheManager->refresh(array(
  'context_settings' => array('contexts' => array('web', 'web2')
));`

**Comment by jaygilmore** [comment]
Fixed. Thanks for catching the error.
