### ISSUE TITLE
[Edit Suggestion] modX.regClientStartupScript

### ISSUE THREAD

**Issue by jcdm** [modxcms/docs#217]
## Page Title
modX.regClientStartupScript

## URL
https://docs.modx.com/revolution/2.x/developing-in-modx/other-development-resources/class-reference/modx/modx.regclientstartupscript

## Issue or Suggestion
The last example starts $modx->re[f]Client... rather than $modx->re[g]Client...

**Comment by Jako** [comment]
Thanks!
