### ISSUE TITLE
[Edit Suggestion] SimpleSearch.SimpleSearch

### ISSUE THREAD

**Issue by tonyklapatch** [modxcms/docs#218]
## Page Title
SimpleSearch.SimpleSearch

## URL
https://docs.modx.com/extras/revo/simplesearch/simplesearch.simplesearch

## Issue or Suggestion

The "includeTVList" parameter is missing from the documentation. 

For future reference, this param is referenced in "core/components/simplesearch/model/simplesearch/driver/simplesearchdriverbasic.class.php"

**Comment by dimitrihilverda** [comment]
Added it to the docs
