### ISSUE TITLE
Correction to MODx Revo Instructions

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#22]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [8695](https://modx.zendesk.com/agent/#/tickets/8695)
**Priority:** 
**Zendesk assignee:** MODX Support/Jay Gilmore

**Original ticket content:**

Hi,

Re: http://rtfm.modx.com/revolution/2.x/administering-your-site/security/security-tutorials/giving-a-user-manager-access

Suggestion in blue
Correction in red

[My notes in grey]

First off, create your user [add link to instruction on how to do this]. Then:

1. In Access Controls | Roles create a new role (say, Editor) with an authority of say, 10.

2. In Access Controls | User Groups add the User to the "Administrator" group with a role of "Editor"

3. In Access Controls | Access Policies, duplicate the administrator policy and rename it to whatever you want, say "AdminLite". [you used AdminLite in the text below]

a. [Indent] Edit this AdminLite Policy to use whatever Permissions you want the User to have.

4. In Access Controls | User Groups, right click on the "Administrator" group and select "Update Group."

a. [Indent] On the Context Access tab, add two new entries to the grid:

1. [Indent] Context: 'mgr' Minimum Role: 'Editor', Access Policy 'AdminLite'

2. [Indent] Context: 'web' Minimum Role: 'Editor', Access Policy 'Load, List and View'

5. Click on Security -> Flush Sessions and re-login.

I would also recommend adding a breakdown of what each of these step actually does.

Many thanks,

AxMann

**Comment by jaygilmore** [comment]
*Comment from Zendesk by x@taintedmirror.com at 2014-06-04 08:47:48 UTC:*

<p>Hi,</p>

<p>Re: <a href="http://rtfm.modx.com/revolution/2.x/administering-your-site/security/security-tutorials/giving-a-user-manager-access" rel="nofollow" target="_blank">http://rtfm.modx.com/revolution/2.x/administering-your-site/security/security-tutorials/giving-a-user-manager-access</a></p>

<p>Suggestion in blue
<br />Correction in red</p>

<p>[My notes in grey]</p>

<p>First off, create your user [add link to instruction on how to do this]. Then:</p>

<p>1. In Access Controls | Roles create a new role (say, Editor) with an authority of say, 10.</p>

<p>2. In Access Controls | User Groups add the User to the &quot;Administrator&quot; group with a role of &quot;Editor&quot;</p>

<p>3. In Access Controls | Access Policies, duplicate the administrator policy and rename it to whatever you want, say &quot;AdminLite&quot;. [you used AdminLite in the text below]</p>

<p>a. [Indent] Edit this AdminLite Policy to use whatever Permissions you want the User to have.</p>

<p>4. In Access Controls | User Groups, right click on the &quot;Administrator&quot; group and select &quot;Update Group.&quot;</p>

<p>a. [Indent] On the Context Access tab, add two new entries to the grid:</p>

<p>1. [Indent] Context: &#39;mgr&#39; Minimum Role: &#39;Editor&#39;, Access Policy &#39;AdminLite&#39;</p>

<p>2. [Indent] Context: &#39;web&#39; Minimum Role: &#39;Editor&#39;, Access Policy &#39;Load, List and View&#39;</p>

<p>5. Click on Security -&gt; Flush Sessions and re-login.</p>

<p>I would also recommend adding a breakdown of what each of these step actually does.</p>

<p>Many thanks,</p>

<p>AxMann</p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2014-11-18 21:34:29 UTC:*

<p>Hi Axel,</p>
<p>I am not sure why your request was never answered. I will place this on hold until we can review.</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by dubrod** [comment]
wording and proper naming updated
