### ISSUE TITLE
[Edit Suggestion] HybridAuth

### ISSUE THREAD

**Issue by tonyklapatch** [modxcms/docs#221]
## Page Title
HybridAuth

## URL
https://docs.modx.com/extras/revo/hybridauth

## Issue or Suggestion

YouTube video embed is trying to load over HTTP instead of HTTPs which is blocked due to mixed content. Also "Fist of all watch this video" should be "First..."

**Comment by Mark-H** [comment]
Corrected, thank you for logging an issue.
