### ISSUE TITLE
[Edit Suggestion] modX.makeUrl

### ISSUE THREAD

**Issue by Lefthandmedia** [modxcms/docs#223]
## Page Title
modX.makeUrl

## URL
https://docs.modx.com/revolution/2.x/developing-in-modx/other-development-resources/class-reference/modx/modx.makeurl

## Issue or Suggestion

the first lines states that the third argument should be s string.
This should be 'mixed' because the third example `$url = $modx->makeUrl(25, '', array('hello' => 'world'));`  shows also an array can be used.

**Comment by Mark-H** [comment]
Turned it into string|array, thanks for logging an issue.
