### ISSUE TITLE
[Edit Suggestion] Creating a 3rd Party Component Build Script

### ISSUE THREAD

**Issue by Lefthandmedia** [modxcms/docs#225]
## Page Title
Creating a 3rd Party Component Build Script

## URL
https://docs.modx.com/revolution/2.x/developing-in-modx/advanced-development/package-management/creating-a-3rd-party-component-build-script

## 
In the section 'Starting the Build Script' it doesn't say what file this is supposed to be. what is the name of the file that this code needs to go in? (build.transport.php ??)

**Comment by Mark-H** [comment]
Yeah, `_build/build.transport.php` typically. That's not required but fairly standard. Updated the docs, thanks!
