### ISSUE TITLE
Formit email validation not working

### ISSUE THREAD

**Issue by eremozin** [modxcms/docs#226]
```
[[!FormIt? 
&hooks=`spam,redirect,email` 
&validate=`workemail:blank,company:required,name:required,email:email:required` 
&emailTpl=`contact-email-tpl` 
&emailSubject=`[[*pagetitle]] ` 
&emailTo=`[[++client-email-receiver]]` 
&emailFrom=`noreply@customer.com` 
&emailFromName=`customer.com` 
&redirectTo=`[[*id:FirstChildId]]`
&emailReplyTo=`[[+email]]`
]]
```

**Comment by matdave** [comment]
This belongs in https://github.com/sterc/formit/issues but also, the FormIt processor doesn't currently allow system settings in the emailTo field. You would need a hook that set's email to use a custom system setting.

**Comment by Jako** [comment]
Using a system setting in emailTo should work, but you are right, it is a FormIt issue and not a MODX Docs issue.
