### ISSUE TITLE
[Edit Suggestion] Dead link

### ISSUE THREAD

**Issue by apboon** [modxcms/docs#228]
## Page Title
Explanation of Directory Structure

## URL
https://docs.modx.com/revolution/2.x/getting-started/an-overview-of-modx/glossary-of-revolution-terms/explanation-of-directory-structure

## Issue or Suggestion
Link ("Creating a 3rd Party Component") to non-existing URI: https://docs.modx.com/display/~splittingred/2008/06/26/Writing+a+3rd+Party+Component+in+MODX+Revolution%2C+Pt.+I

**Comment by Mark-H** [comment]
Fixed, thanks! Should've been https://docs.modx.com/revolution/2.x/case-studies-and-tutorials/developing-an-extra-in-modx-revolution
