### ISSUE TITLE
[Edit Suggestion] Loading MODX Externally

### ISSUE THREAD

**Issue by fonpixel** [modxcms/docs#237]
## Page Title
Loading MODX Externally

## URL
https://docs.modx.com/revolution/2.x/developing-in-modx/other-development-resources/loading-modx-externally

## Issue or Suggestion

**Comment by fonpixel** [comment]
In a first line of the first example need to change this line
require_once '/absolute/path/to/modx/config.**core**.php';
to this
require_once '/absolute/path/to/modx/config.**inc**.php';

**Comment by Mark-H** [comment]
No, that example is correct. You're loading the `config.core.php` file from the root of the site to get access to the `MODX_CORE_PATH` and `MODX_CONFIG_KEY` constants, which the next require will use to get the `core/config/config.inc.php` file.

**Comment by fonpixel** [comment]
Yes, you're right!
I thought, that a path to the core config.
Thank you for your help!
