### ISSUE TITLE
Populate Github Issue creation with Page title and URL

### ISSUE THREAD

**Issue by zaigham** [modxcms/docs#24]
It would be awesome if "Suggest Edit" link from MODX RTFM takes the user to pre-populated issue.
Example: ``` https://github.com/modxcms/docs/issues/new?title=[Edit%20Suggestion]%20Customizing%20the%20Manager%20via%20Plugins&body=http://rtfm.modx.com/revolution/2.x/administering-your-site/customizing-the-manager/customizing-the-manager-via-plugins ```

![screenshot_021215_120303_pm](https://cloud.githubusercontent.com/assets/114390/6163082/180716fa-b2af-11e4-96d5-b9590d702173.jpg)

**Comment by zaigham** [comment]
This might be helpful: http://archetyped.com/know/guided-github-reports/

**Comment by rthrash** [comment]
That is a really really cool find Zi … thanks for sharing! :+1:

**Comment by jaygilmore** [comment]
This is brilliant Zi, I'll get this in place today.

**Comment by jaygilmore** [comment]
This is now implemented. 
![new_issue_ _modxcms_docs](https://cloud.githubusercontent.com/assets/378199/6178188/010482b0-b2e3-11e4-887c-11a6077b1499.png)

**Comment by rthrash** [comment]
What took you so long??? :P

**Comment by zaigham** [comment]
You are all welcome. :laughing:
