### ISSUE TITLE
"Become an editor" wrong error

### ISSUE THREAD

**Issue by ant-tar** [modxcms/docs#247]
Go to any inner Docs page, f.e. https://docs.modx.com/revolution/2.x/getting-started  scroll to bottom and find 
> Suggest an edit to this page on GitHub (Requires GitHub account. Opens a new window/tab) or become an editor of the MODX Documentation. 

**become an editor**   goes to at https://modxos.wufoo.com/forms/become-a-modx-documentation-editor/  and this link is wrong.

So how can I become an editor?

**Comment by jaygilmore** [comment]
@himurovich. Thank you for letting us know. We apologize for the mistake. We have corrected the form and it should now work for you.
