### ISSUE TITLE
[Edit Suggestion] SimpleSearch.SimpleSearch.containerTpl

### ISSUE THREAD

**Issue by yneshchadim** [modxcms/docs#249]
## Page Title
SimpleSearch.SimpleSearch.containerTpl

## URL
https://docs.modx.com/extras/revo/simplesearch/simplesearch.simplesearch/simplesearch.simplesearch.containertpl

## Issue or Suggestion

**Comment by Mark-H** [comment]
Please add an issue or suggestion if there's something wrong with that page, thanks :)
