### ISSUE TITLE
[Edit Suggestion] Create a Multilingual Website with migxMultiLang

### ISSUE THREAD

**Issue by muzzwood** [modxcms/docs#25]
## Page Title

Create a Multilingual Website with migxMultiLang
## URL

http://rtfm.modx.com/revolution/2.x/case-studies-and-tutorials/create-a-multilingual-website-with-migxmultilang
## Issue or Suggestion

Hi, I wrote this tutorial but my name was spelled incorrectly. 
It should be "Murray Wood"
Cheers!

**Comment by jaygilmore** [comment]
Murray, 

I've corrected your user account first name. Cheers, 

Jay
