### ISSUE TITLE
Creating a Blog in MODx Revolution

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#3]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [11394](https://modx.zendesk.com/agent/#/tickets/11394)
**Priority:** 
**Zendesk assignee:** MODX Support/A

**Original ticket content:**

-- ISSUE DETAILS --
Creating a Blog in MODx Revolution (68)
http://rtfm.modx.com/revolution/2.x/case-studies-and-tutorials/creating-a-blog-in-modx-revolution.

There's a mistake in a piece of code under the "Setting up the blogPost Chunk" headline. The following line:

5: [[!tolinks? &items=`[[+tv.tags]]` &tagKey=`tag` &target=`1`]]

Should be replaced with

5: [[!tolinks? &items=`[[+tv.tags]]` &tagKey=`tags` &target=`1`]]

Otherwise, clicking tag links displays an empty page.

Thanks,

Andrey

**Comment by jaygilmore** [comment]
*Comment from Zendesk by korovin.andrey@gmail.com at 2015-02-09 15:22:58 UTC:*

<p>-- ISSUE DETAILS --
<br />Creating a Blog in MODx Revolution (68)
<br /><a href="http://rtfm.modx.com/revolution/2.x/case-studies-and-tutorials/creating-a-blog-in-modx-revolution" rel="nofollow" target="_blank">http://rtfm.modx.com/revolution/2.x/case-studies-and-tutorials/creating-a-blog-in-modx-revolution</a>.</p>

<p>There&#39;s a mistake in a piece of code under the &quot;Setting up the blogPost Chunk&quot; headline. The following line:</p>

<p>5: [[!tolinks? &amp;items=`[[+tv.tags]]` &amp;tagKey=`tag` &amp;target=`1`]]</p>

<p>Should be replaced with</p>

<p>5: [[!tolinks? &amp;items=`[[+tv.tags]]` &amp;tagKey=`tags` &amp;target=`1`]]</p>

<p>Otherwise, clicking tag links displays an empty page.</p>

<p>Thanks,</p>

<p>Andrey</p>

**Comment by dubrod** [comment]
added the "s"
