### ISSUE TITLE
[Edit Suggestion] Lingua

### ISSUE THREAD

**Issue by carnevlu** [modxcms/docs#32]
## Page Title

Lingua
## URL

http://rtfm.modx.com/extras/revo/lingua
## Issue or Suggestion

add incompatibility issues with:
- Content Blocks from modmore (https://www.modmore.com/extras/contentblocks/)

**Comment by goldsky** [comment]
@Mark-H
how does Content Block work?

**Comment by Mark-H** [comment]
Not like the average add-on ;)

It uses jQuery to replace the content field with a dynamic content canvas
consisting of layouts (rows with columns) and fields (blocks of content).
When the resource gets saved, it turns the data in the canvas into an array
that is posted along with the data. A plugin intercepts that, parses the
data into markup and sets it in the resource content, saving the canvas
array in the resource properties.

How to make that work with Lingua? I don't know yet..
Op 9 mrt. 2015 18:52 schreef "rico" notifications@github.com:

**Comment by goldsky** [comment]
OK, then.
It's clarified that Lingua can not manipulate ContentBlock.
Doc has been updated.
