### ISSUE TITLE
RTFM Issue for the page: getResources

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#4]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [11386](https://modx.zendesk.com/agent/#/tickets/11386)
**Priority:** 
**Zendesk assignee:** MODX Support/A

**Original ticket content:**

hideContainers 	If set, will not show any Resources marked as a 
container (is_folder). 	0

In the parentheses, the tag name is correctly: *isfolder*.

Should be also mentioned that, if resource is not a container, then 
[[+isfolder]] placeholder _will not be set_.
Although this might be a bug, because this placeholder should have been 
set to zero.

-- ISSUE DETAILS --
getResources (654)
http://rtfm.modx.com/extras/revo/getresources.

**Comment by jaygilmore** [comment]
*Comment from Zendesk by vhollo@gmail.com at 2015-02-07 18:35:51 UTC:*

<p>hideContainers 	If set, will not show any Resources marked as a 
<br />container (is_folder). 	0</p>

<p>In the parentheses, the tag name is correctly: *isfolder*.</p>

<p>Should be also mentioned that, if resource is not a container, then 
<br />[[+isfolder]] placeholder _will not be set_.
<br />Although this might be a bug, because this placeholder should have been 
<br />set to zero.</p>

<p>-- ISSUE DETAILS --
<br />getResources (654)
<br /><a href="http://rtfm.modx.com/extras/revo/getresources" rel="nofollow" target="_blank">http://rtfm.modx.com/extras/revo/getresources</a>.</p>

**Comment by dubrod** [comment]
is_folder changed
