### ISSUE TITLE
[Edit Suggestion] FormIt.Hooks.FormItSaveForm

### ISSUE THREAD

**Issue by ahaller** [modxcms/docs#43]
## Page Title

FormIt.Hooks.FormItSaveForm
## URL

http://rtfm.modx.com/extras/revo/formit/formit.hooks/formit.hooks.formitsaveform
## Issue or Suggestion

formEncrypt - The instructions should read: "If is set to '**1**'...", instead of "If set to 'true'...". The reason is because the mysql key is a _tinyint_ and not a _boolean_.

**Comment by pixelchutes** [comment]
All set.

http://rtfm.modx.com/extras/revo/formit/formit.hooks/formit.hooks.formitsaveform
