### ISSUE TITLE
[Edit Suggestion] Adding CSS and JS to Your Pages Through Snippets

### ISSUE THREAD

**Issue by Lefthandmedia** [modxcms/docs#49]
## Page Title

Adding CSS and JS to Your Pages Through Snippets
## URL

http://rtfm.modx.com/revolution/2.x/developing-in-modx/basic-development/snippets/adding-css-and-js-to-your-pages-through-snippets
## Issue or Suggestion

there is a typo halfway the page where it says 

refClientStartupScript (note: reFclient instead of reGclient)

**Comment by Mark-H** [comment]
Thanks, fixed (twice) ;)
