### ISSUE TITLE
Polls.PollsLatest paramater issue

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#5]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [11143](https://modx.zendesk.com/agent/#/tickets/11143)
**Priority:** 
**Zendesk assignee:** MODX Support/Jay Gilmore

**Original ticket content:**

In subtitle <h3 
id="Polls.PollsLatest-tplVoteAnswers">tplVoteAnswers</h3> there is a bug 
in parameter name - addes "s". Right subtitle is tplVoteAnswer (without s).

-- ISSUE DETAILS --
Polls.PollsLatest (953)
http://rtfm.modx.com/extras/revo/polls/polls.pollslatest.

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jiri@pavlicek.cz at 2015-01-21 21:58:40 UTC:*

<p>In subtitle &lt;h3 
<br />id=&quot;Polls.PollsLatest-tplVoteAnswers&quot;&gt;tplVoteAnswers&lt;/h3&gt; there is a bug 
<br />in parameter name - addes &quot;s&quot;. Right subtitle is tplVoteAnswer (without s).</p>

<p>-- ISSUE DETAILS --
<br />Polls.PollsLatest (953)
<br /><a href="http://rtfm.modx.com/extras/revo/polls/polls.pollslatest" rel="nofollow" target="_blank">http://rtfm.modx.com/extras/revo/polls/polls.pollslatest</a>.</p>

<p>-- 
<br />Jiří Pavlíček
<br />+420 602 802 183, +420 561 116 536</p>

<p>weby | webdesign | e-commerce | intranet</p>

<p><a href="http://www.pavlicek.cz" rel="nofollow" target="_blank">www.pavlicek.cz</a>
<br /><a href="mailto:jiri@pavlicek.cz">jiri@pavlicek.cz</a></p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2015-01-22 17:33:54 UTC:*

<p>Thanks for the report. We will review and fix as soon as time permits.</p>
<p>All the best,</p>
<p>Jay</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by dubrod** [comment]
<h3 id="Polls.PollsLatest-tplVoteAnswer">tplVoteAnswer</h3>  changed
