### ISSUE TITLE
[Edit Suggestion] Adding CSS and JS to Your Pages Through Snippets

### ISSUE THREAD

**Issue by Lefthandmedia** [modxcms/docs#50]
## Page Title

Adding CSS and JS to Your Pages Through Snippets
## URL

http://rtfm.modx.com/revolution/2.x/developing-in-modx/basic-development/snippets/adding-css-and-js-to-your-pages-through-snippets
## Issue or Suggestion

in the paragraph about **Adding Before the BODY End** 2 of the 3 examples have _regClientStartupScript_ instead of the correct _regClientScript_.
This is confusing

**Comment by Mark-H** [comment]
Thanks for reporting, fixed.
