### ISSUE TITLE
[Edit Suggestion] Moving Your Site to a New Server, or to Root from Subfolder

### ISSUE THREAD

**Issue by chrisdempsey** [modxcms/docs#56]
## Page Title

Moving Your Site to a New Server, or to Root from Subfolder
## URL

http://rtfm.modx.com/revolution/2.x/administering-your-site/moving-your-site-to-a-new-server
## Issue or Suggestion

Typo on page heading:

> Moving Your Site to a New Server, or to Root from Subfolder (publishing suffolder or development site)

su**ff**older should be subfolder.

**Comment by Mark-H** [comment]
Thanks for the report; fixed the typo.
