### ISSUE TITLE
Restricting an Element from Users page, update for 2.3 UI

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#6]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [11350](https://modx.zendesk.com/agent/#/tickets/11350)
**Priority:** 
**Zendesk assignee:** MODX Support/Jay Gilmore

**Original ticket content:**

Hi,

Can this page get updated for Revlution 2.3 please…it is incredibly frustrating trying to figure out what to do when it is written for the old UI.

Thanks

Matt

-- ISSUE DETAILS --
Restricting an Element from Users (486)
http://rtfm.modx.com/revolution/2.x/administering-your-site/security/security-tutorials/restricting-an-element-from-users.

**Comment by jaygilmore** [comment]
*Comment from Zendesk by matt.jonat@smartershows.com at 2015-02-05 13:15:57 UTC:*

<p>Hi,</p>

<p>Can this page get updated for Revlution 2.3 please…it is incredibly frustrating trying to figure out what to do when it is written for the old UI.</p>

<p>Thanks</p>

<p>Matt</p>

<p>-- ISSUE DETAILS --
<br />Restricting an Element from Users (486)
<br /><a href="http://rtfm.modx.com/revolution/2.x/administering-your-site/security/security-tutorials/restricting-an-element-from-users" rel="nofollow" target="_blank">http://rtfm.modx.com/revolution/2.x/administering-your-site/security/security-tutorials/restricting-an-element-from-users</a>.</p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2015-02-05 14:18:23 UTC:*

<p>Hi Matt,</p>
<p>Thanks for the report. Yes, I can imagine it&#39;s frustrating. I&#39;ll share this with the documentation team and we will review and fix as soon as time permits.</p>
<p>All the best,</p>
<p>Jay</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by ghost** [comment]
Done.

**Comment by jaygilmore** [comment]
Thanks so much @sottwell.
