### ISSUE TITLE
[Edit Suggestion] If

### ISSUE THREAD

**Issue by tilmanj** [modxcms/docs#67]
## Page Title

If
## URL

http://rtfm.modx.com/extras/revo/if
## Issue or Suggestion

There is something wrong with this:
[[!If? &subject=`[[+gallery.id]]` &operator=`isempty` &then:`<p>Test</p>` &debug=`1`]]
Array
(
    [subject] => 
    [operator] => isempty
    [operand] => 
    [then] => 
    [else] => 
    [debug] => 1
)
string(0) ""
So subject is empty! But no execution of then!

**Comment by Mark-H** [comment]
Try `[[If` instead of `[[!If`. Uncached is always parsed later than cached placeholders, so gallery.id wont exist anymore. Old, but still accurate: https://www.markhamstra.com/modx/2011/11/nested-caching-in-modx-revolution/
