### ISSUE TITLE
[Edit Suggestion] Image+

### ISSUE THREAD

**Issue by Jako** [modxcms/docs#68]
## Page Title

Image+
## URL

https://rtfm.modx.com/extras/revo/image
## Issue or Suggestion

**Please change this:**
### What is Image+?

Image+ is an advanced image custom template variable type for MODx Revolution. The dimensions for the uploaded image can (optionally) be configured to constrain a minimal width and/or height. The image crop could be forced to remain at a pre-set ratio. A graphical tool could be used to crop the image to the required dimensions/proportions.
### Requirements
- MODX Revolution 2.2.4+
- PHP v5.3+
- MODX Cropping Engine i.e. [pThumb](http://modx.com/extras/package/pthumb)
### History & Info

The Image+ project was started in 2012 by [Alan Pich](https://github.com/alanpich), and is maintained and developed further since 2015 by [Thomas Jakobi](https://github.com/jako).
### Download

Image+ can be downloaded from within the MODX Revolution manager via Package Management, or from the MODx Extras Repository, available on http://modx.com/extras/package/imageplustvinput
### Development & Bug Reporting

Image+ has a GitHub repository on https://github.com/Jako/ImagePlus
### Documentation

The package documentation could be found on http://jako.github.io/ImagePlus/

**and please remove the Usage part**

**Comment by ghost** [comment]
Done.

**Comment by Jako** [comment]
Thank you Susan.
