### ISSUE TITLE
Creating a Blog in MODx Revolution Furls/Archivist

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#7]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [11147](https://modx.zendesk.com/agent/#/tickets/11147)
**Priority:** 
**Zendesk assignee:** MODX Support/A

**Original ticket content:**

Guys,

If you're using friendly URLs Archivist won't work as expected. What needs to happen is a RewriteRule needs to be added into htaccess. I would suggest this should be added into the post to help anyone trying to impelement a blog. The issue and solution is described at http://owanhunte.com/blog/entry/make-friendly-urls-work-in-modx-with-apache-rewrite-rules.html

-- ISSUE DETAILS --
Creating a Blog in MODx Revolution (68)
http://rtfm.modx.com/revolution/2.x/case-studies-and-tutorials/creating-a-blog-in-modx-revolution.

**Comment by jaygilmore** [comment]
*Comment from Zendesk by nick.shelomanov@gmail.com at 2015-01-22 09:51:59 UTC:*

<p>Guys,</p>

<p>If you&#39;re using friendly URLs Archivist won&#39;t work as expected. What needs to happen is a RewriteRule needs to be added into htaccess. I would suggest this should be added into the post to help anyone trying to impelement a blog. The issue and solution is described at <a href="http://owanhunte.com/blog/entry/make-friendly-urls-work-in-modx-with-apache-rewrite-rules.html" rel="nofollow" target="_blank">http://owanhunte.com/blog/entry/make-friendly-urls-work-in-modx-with-apache-rewrite-rules.html</a></p>

<p>-- ISSUE DETAILS --
<br />Creating a Blog in MODx Revolution (68)
<br /><a href="http://rtfm.modx.com/revolution/2.x/case-studies-and-tutorials/creating-a-blog-in-modx-revolution" rel="nofollow" target="_blank">http://rtfm.modx.com/revolution/2.x/case-studies-and-tutorials/creating-a-blog-in-modx-revolution</a>.</p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2015-01-22 14:54:19 UTC:*

<p>Thanks for the report. We will review and fix as soon as time permits.</p>
<p>All the best,</p>
<p>Jay</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by dubrod** [comment]
updated
