### ISSUE TITLE
[Edit Suggestion] Slideshow Manager

### ISSUE THREAD

**Issue by tilmanj** [modxcms/docs#74]
## Page Title

Slideshow Manager
## URL

https://rtfm.modx.com/extras/revo/slideshow-manager
## Issue or Suggestion

Is it possible to make the images width 100% and height auto on smaller screens? The slideshow destroys the layout when I want to use it on smartphone/iphone!

**Comment by Mark-H** [comment]
Please consult the developer of the extra. This repository is only for issues with the documentation.
