### ISSUE TITLE
Slideshow Manager image size 204x100px shows incorrectly

### ISSUE THREAD

**Issue by eiger3970** [modxcms/docs#78]
## Page Title

Slideshow Manager
## URL

https://rtfm.modx.com/extras/revo/slideshow-manager
## Issue or Suggestion

Images don't show properly.
My image size needs to be 204x100px, but the slide show only shows the top 20px enlarged and grainy?

**Comment by Mark-H** [comment]
Please consult with the developer for issues and bug reports, this repo is only for documentation issues.
