### ISSUE TITLE
xPDO.getObjectGraph example issue

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/docs#8]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [10884](https://modx.zendesk.com/agent/#/tickets/10884)
**Priority:** 
**Zendesk assignee:** MODX Support/A

**Original ticket content:**

Hello,

The Example how to use the getTVValue Helper Function is wrong.
This must be called

|return| |$page||->getTVValue(||'my_tv_name'||);|

instead of

|return| |$modx||->getTVValue(||'my_tv_name'||);|

greetings,
Julian Hirche

-- ISSUE DETAILS --
xPDO.getObjectGraph (1246)
http://rtfm.modx.com/xpdo/2.x/class-reference/xpdo/xpdo.getobjectgraph.

---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by jaygilmore** [comment]
*Comment from Zendesk by julian.hirche@gmx.de at 2014-12-21 19:06:34 UTC:*

<p>Hello,</p>

<p>The Example how to use the getTVValue Helper Function is wrong.
<br />This must be called</p>

<p>|return| |$page||-&gt;getTVValue(||&#39;my_tv_name&#39;||);|</p>

<p>instead of</p>

<p>|return| |$modx||-&gt;getTVValue(||&#39;my_tv_name&#39;||);|</p>

<p>greetings,
<br />Julian Hirche</p>

<p>-- ISSUE DETAILS --
<br />xPDO.getObjectGraph (1246)
<br /><a href="http://rtfm.modx.com/xpdo/2.x/class-reference/xpdo/xpdo.getobjectgraph" rel="nofollow" target="_blank">http://rtfm.modx.com/xpdo/2.x/class-reference/xpdo/xpdo.getobjectgraph</a>.</p>

<p>---
<br />Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
<br /><a href="http://www.avast.com" rel="nofollow" target="_blank">http://www.avast.com</a></p>

**Comment by jaygilmore** [comment]
*Comment from Zendesk by jay@modx.com at 2014-12-22 15:51:40 UTC:*

<p>Thanks for the report. We will review and make any fixes, if needed, as soon as time permits.</p>
<p>All the best,</p>
<p>Jay</p>
<p>Jay Gilmore<br>
Customer Development and Delight</p>

**Comment by dubrod** [comment]
updated
