### ISSUE TITLE
Modx - Login Extra not working in modx 2.3

### ISSUE THREAD

**Issue by classic-620** [modxcms/docs#83]
Hi All,

We are using modx 2.3.3 and using the Login Extra to facilitates the front end user to access some pages other than normal pages. After login page the user successfully redirect to target page but session is not keep working for rest of pages or even for target page. So we are not able to get either user is logged in or logout.

kindly help me over this and tell me that how login user session can be maintained via Login extra.

Thanks
Praveen Shukla

**Comment by Mark-H** [comment]
This repository is only for reporting specific issues related to the docs. Please consult the forum or the community on slack via modx.org for help with your Login issue.
