### ISSUE TITLE
[Edit Suggestion] OnDocFormRender

### ISSUE THREAD

**Issue by jakub-gawryl** [modxcms/docs#85]
## Page Title

OnDocFormRender
## URL

https://rtfm.modx.com/revolution/2.x/developing-in-modx/basic-development/plugins/system-events/ondocformrender
## Issue or Suggestion

Event parameters: 
"resource - A reference to the modResource object. Will be null for new Resources."

In MODx 2.3.3 for 'new' Resource it's not null - it's pointin' to newly created (not saved) modResource object: [create.class.php:76](https://github.com/modxcms/revolution/blob/master/manager/controllers/default/resource/create.class.php#L76)

I created a [pull request](https://github.com/modxcms/revolution/pull/12535/files) to add ability to pre fill fields in new resource using $resource.

**Comment by Mark-H** [comment]
Thanks, added.
