### ISSUE TITLE
[Edit Suggestion] ImportX

### ISSUE THREAD

**Issue by nicboyde** [modxcms/docs#87]
## Page Title

ImportX
## URL

https://rtfm.modx.com/extras/revo/importx
## Issue or Suggestion

Under: "Here's some CSV-related notes:", add:

4 Any paragraph breaks in your imported data will contain "\n", or new-line characters. These must be removed, or replaced with something else, as ImportX wrongly recognises them as end-of-record markers.

5 CSV files quite often have an extra blank record appended at the end. You may need to remove this last record using something like Notepad++.

**Comment by Mark-H** [comment]
Added, thanks.
