### ISSUE TITLE
[Edit Suggestion] Nginx Server Config

### ISSUE THREAD

**Issue by gottaloveit** [modxcms/docs#90]
## Page Title

Nginx Server Config
## URL

https://rtfm.modx.com/revolution/2.x/getting-started/installation/basic-installation/nginx-server-config
## Issue or Suggestion

Remove the auto formatting of urls since i'm pretty sure the config here for Nginx would fail pretty bad with those server names

![untitled](https://cloud.githubusercontent.com/assets/316801/9267688/d55d69ba-4207-11e5-8d88-f3b0f5d4d70d.png)

**Comment by Mark-H** [comment]
Yep, that would fail pretty hard.
